#! /bin/bash

#
#   Copyright (C) 2016, Jaguar Land Rover. All Rights Reserved.
#
#   This Source Code Form is subject to the terms of the Mozilla Public
#   License, v. 2.0. If a copy of the MPL was not distributed with this file,
#   You can obtain one at http://mozilla.org/MPL/2.0/.
#

echo "Destroying the VSI shared memory segments on disk..."

rm -f /var/run/shm/vsiCoreDataStore
rm -f /var/run/shm/vsiPageTableStore

echo "   The VSI system has been cleared"
