#! /usr/local/bin/lua

require ( "liblua_vsi_core" )

print ( "\nLua wrapper - open/close test...\n" )

handle, statusString = Lua_vsiCoreOpen()
print ( handle, statusString )

Lua_vsiCoreClose ( handle )
