#! /bin/bash

#
#   Copyright (C) 2016-2017, Jaguar Land Rover. All Rights Reserved.
#
#   This Source Code Form is subject to the terms of the Mozilla Public
#   License, v. 2.0. If a copy of the MPL was not distributed with this file,
#   You can obtain one at http://mozilla.org/MPL/2.0/.
#

VSIroot=/home/dmies/git/vsi_bridge/vsi/src
VSSroot=/home/dmies/git/vsi_bridge/vss

echo ""
echo "Clearing the shared memory segments..."
rm -f /var/run/shm/vsi*DataStore

echo ""
echo "Importing the VSS definitions..."
$VSIroot/importVSS $VSIroot/$1

echo ""
echo "Dumping the contents of the shared memory segments..."
# $VSIroot/dump
gdb $VSIroot/dump

echo ""
echo "===> The VSI system has been cleared and reinitialized"
echo ""
