#! /usr/local/bin/lua

--[[
    Copyright (C) 2016, Jaguar Land Rover. All Rights Reserved.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this file,
    You can obtain one at http://mozilla.org/MPL/2.0/.
--]]

require ( "liblua_vsi_core" )

print ( "\nLua wrapper - Insert test...\n" )

handle, statusString = Lua_vsiCoreOpen()
print ( handle, statusString )

print ( "Inserting signal 0,2 into VSI core" );
Lua_vsiCoreInsert ( 0, 2, 222 );

Lua_vsiCoreClose ( handle )

