#! /usr/local/bin/lua

--[[
    Copyright (C) 2016, Jaguar Land Rover. All Rights Reserved.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this file,
    You can obtain one at http://mozilla.org/MPL/2.0/.
--]]

require ( "liblua_vsi_core" )

print ( "\nLua wrapper - open/close test...\n" )

handle, statusString = Lua_vsiCoreOpen()
print ( handle, statusString )

Lua_vsiCoreClose ( handle )
